### ISSUE TITLE
Open discussions

### ISSUE THREAD

**Issue by ippocratis** [pixincreate/mGMSCompat#3]
Since its really early days its more suited to talk thoughts ides etc in discussions

I see  you updated readme with some concerns about locked bl

I'm pretty sure it will not require a locked BL state
I have used voltageos and currently using sparkos with an unlocked bootloader
both rom have gmscompat implementd

On the other hand Root sure by design os needed
 it's a magisk module after all

I love the idea behimd gsmcompat

I hope you manage to give shape to a magisk module

**Comment by pixincreate** [comment]
Hi @ippocratis, I'm open to all the suggesstions if that helps develop this project. I was busy with my office work and yes, I did some homework regarding the bootloader requirement and I found that there actually exist some project targetting GrapheneOS's verified boot requirement. Even ProtonAOSP passes the safetynet while having GMSCompat. With all these said, I've opened the discussions section where not only you but anyone can contribute their ideas and suggesstions that help improve mGMSCompat.   

Please refer #5 for more info on this. Many thanks!
